from typing import Any

from pydantic import Field

from v4vapp_backend_v2.hive_models.amount_pyd import AmountPyd
from v4vapp_backend_v2.hive_models.op_base import OpBase
from v4vapp_backend_v2.process.lock_str_class import CustIDType


class LimitOrderCancelled(OpBase):
    """Model for Hive virtual limit_order_cancelled operations.

    These operations are generated by the blockchain when a previously-created
    limit order is cancelled automatically (for example, due to expiration or
    other system conditions).  The fields mirror the raw event data returned by
    Hive.

    Attributes:
        amount_back (AmountPyd): The amount returned to the seller (HBD/HIVE).
        orderid (int): The identifier of the cancelled order.
        seller (str): Account that owned the order.
        cust_id (CustIDType): Customer id for internal tracking; defaults to seller.
    """

    amount_back: AmountPyd
    orderid: int
    seller: str
    cust_id: CustIDType = Field("", description="Customer ID determined from seller field")

    def __init__(self, **data: Any):
        super().__init__(**data)
        # use seller as default cust_id so downstream code can still access it
        self.cust_id = self.seller

    @property
    def log_str(self) -> str:
        return f"🔁 {self.seller} cancelled order {self.orderid} returned {self.amount_back} {self.link} {self.short_id}"

    @property
    def notification_str(self) -> str:
        return f"{self.seller} cancelled order {self.orderid} and got back {self.amount_back} {self.markdown_link}"
