"""
Overwatch System: End-to-end transaction flow tracking.

This module provides a framework for defining expected transaction flows,
recording events as they occur, and verifying flow completeness.

Core models:

- FlowStage: An expected event (ledger entry or operation) in a flow.
- FlowDefinition: A blueprint for a complete transaction flow.
- FlowEvent: A recorded event that has occurred.
- FlowInstance: A tracked flow instance that collects events and checks completeness.
- Overwatch: Singleton that ingests events, manages active flows, and runs a
  periodic reporting loop.  State is persisted in Redis so it survives restarts.

Usage from db_monitor::

    from v4vapp_backend_v2.process.process_overwatch import Overwatch

    overwatch = Overwatch()                   # singleton
    await overwatch.ingest_ledger_entry(le)   # feed entries
    await overwatch.ingest_op(op)             # feed ops

    # Start the periodic reporter as an asyncio task:
    asyncio.create_task(overwatch.report_loop(interval=30, shutdown_event=evt))
"""

from __future__ import annotations

import asyncio
from collections.abc import Callable
from datetime import datetime, timedelta, timezone
from enum import StrEnum
from typing import Any, ClassVar, Dict, List, Literal

from colorama import Fore
from pydantic import BaseModel, ConfigDict, Field, field_validator

from v4vapp_backend_v2.accounting.ledger_entry_class import LedgerEntry
from v4vapp_backend_v2.accounting.ledger_type_class import LedgerType
from v4vapp_backend_v2.actions.tracked_any import TrackedAny
from v4vapp_backend_v2.config.setup import InternalConfig, logger
from v4vapp_backend_v2.helpers.general_purpose_funcs import find_short_id, from_snake_case
from v4vapp_backend_v2.models.tracked_forward_models import TrackedForwardEvent

ICON = "🌟"

# Redis key prefixes / TTLs
_REDIS_ACTIVE_KEY = "overwatch:flows:active"
_REDIS_COMPLETED_PREFIX = "overwatch:flows:completed:"
_COMPLETED_TTL_SECONDS = 24 * 60 * 60  # 24 hours
_LATE_EVENT_WINDOW = timedelta(seconds=120)  # only absorb late events into recent completions


# ---------------------------------------------------------------------------
# Flow status enum
# ---------------------------------------------------------------------------


class FlowStatus(StrEnum):
    """Status of a flow instance."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    STALLED = "stalled"


# ---------------------------------------------------------------------------
# Flow definition models
# ---------------------------------------------------------------------------


class FlowStage(BaseModel):
    """An expected event within a flow definition.

    A stage can represent either a ledger entry (identified by ledger_type)
    or an operation (identified by op_type). Stages are matched against
    incoming FlowEvents to determine flow progress.
    """

    name: str = Field(..., description="Human-readable stage name")
    event_type: Literal["ledger", "op"] = Field(
        ..., description="Whether this stage expects a ledger entry or an operation"
    )
    ledger_type: LedgerType | None = Field(
        None, description="Expected ledger type (for ledger events)"
    )
    op_type: str | None = Field(None, description="Expected operation type (for op events)")
    required: bool = Field(True, description="Whether this stage must be fulfilled")
    group: str = Field(
        "primary",
        description=(
            "Stage group: 'primary' for events sharing the trigger's short_id, "
            "or a descriptive name for reply-linked events"
        ),
    )
    event_filter: Callable[[FlowEvent], bool] | None = Field(
        None,
        description=(
            "Optional callable that receives the FlowEvent and returns True "
            "if the event genuinely matches this stage.  Used to prevent "
            "false-positive matches when the structural criteria (event_type + "
            "op_type/ledger_type) are ambiguous."
        ),
        exclude=True,  # not serialised to Redis — restored from registered definition
    )
    op_log_str: str = Field("", description="The log string for the operation in this flow stage)")

    model_config = ConfigDict(arbitrary_types_allowed=True)

    def __init__(
        self,
        name: str,
        event_type: Literal["ledger", "op"],
        ledger_type: LedgerType | None = None,
        op_type: str | None = None,
        required: bool = True,
        group: str = "primary",
        event_filter: Callable[[FlowEvent], bool] | None = None,
        op_log_str: str = "",
        **data: Any,
    ) -> None:
        """Explicit initializer helps type checkers.

        Without this method Pylance sees the autogenerated pydantic signature and
        complains that ``op_type``/``ledger_type``/``required`` are missing when
        we call ``FlowStage(...)`` with only the relevant fields.  The logic is
        unchanged; we simply delegate to ``BaseModel.__init__``.
        """
        super().__init__(
            name=name,
            event_type=event_type,
            ledger_type=ledger_type,
            op_type=op_type,
            required=required,
            group=group,
            event_filter=event_filter,
            op_log_str=op_log_str,
            **data,
        )

    def matches(self, event: FlowEvent) -> bool:
        """Check if an event fulfils this stage.

        Ledger events are matched solely by ``ledger_type`` (which is unique
        across stages).  Op events are matched by ``op_type`` alone — group
        disambiguation is not performed here because ``db_monitor`` dispatches
        all events with the default group ``"primary"``.  Deduplication in
        :pymethod:`Overwatch._dispatch` prevents re-arrived trigger updates
        from matching the wrong stage.
        """
        if self.event_type != event.event_type:
            return False
        if self.event_type == "ledger":
            matched = self.ledger_type is not None and self.ledger_type == event.ledger_type
        else:
            # op event: match by op_type only (group-agnostic)
            matched = self.op_type is not None and self.op_type == event.op_type
        if matched and self.event_filter is not None:
            try:
                return self.event_filter(event)
            except Exception:
                return False
        return matched


class FlowDefinition(BaseModel):
    """Blueprint describing the expected stages of a complete transaction flow.

    A flow definition is a named template listing every FlowStage that should
    occur for a particular transaction type. FlowInstances are validated
    against a FlowDefinition to determine completeness.
    """

    name: str = Field(..., description="Flow type identifier (e.g. 'hive_to_keepsats')")
    description: str = Field("", description="Human-readable description")
    trigger_op_type: str = Field(..., description="The op_type that initiates this flow")
    stages: List[FlowStage] = Field(
        default_factory=list, description="Ordered list of expected stages"
    )

    @property
    def required_stages(self) -> List[FlowStage]:
        """Return only the stages marked as required."""
        return [s for s in self.stages if s.required]

    @property
    def stage_names(self) -> List[str]:
        """Return names of all stages."""
        return [s.name for s in self.stages]


# ---------------------------------------------------------------------------
# Flow event and instance models
# ---------------------------------------------------------------------------


class FlowEvent(BaseModel):
    """A recorded event within a flow instance.

    Each event wraps either a LedgerEntry or a TrackedAny operation along
    with identifiers used for matching (group_id, short_id, ledger_type).
    """

    event_type: Literal["ledger", "op"] = Field(..., description="Type of event")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(tz=timezone.utc),
        description="When the event was recorded",
    )
    ledger_entry: LedgerEntry | None = Field(
        None, description="The ledger entry if event_type='ledger'"
    )
    op: Any = Field(None, description="The TrackedAny operation if event_type='op'")
    group_id: str = Field("", description="Group ID from the event source")
    short_id: str = Field("", description="Short ID from the event source")
    ledger_type: LedgerType | None = Field(None, description="Ledger type if applicable")
    op_type: str | None = Field(None, description="Operation type if applicable")
    group: str = Field(
        "primary",
        description="Which group this event belongs to (primary or a reply group name)",
    )
    event_value: str = Field("", description="Optional value for logging or notifications")

    @classmethod
    def from_ledger_entry(
        cls,
        ledger_entry: LedgerEntry,
        group: str = "primary",
    ) -> FlowEvent:
        """Create a FlowEvent from a LedgerEntry."""
        return cls(
            event_type="ledger",
            timestamp=ledger_entry.timestamp,
            ledger_entry=ledger_entry,
            op=None,
            group_id=ledger_entry.group_id,
            short_id=ledger_entry.short_id,
            ledger_type=ledger_entry.ledger_type,
            op_type=None,
            group=group,
            event_value=ledger_entry.formatted_amount(),
        )

    @classmethod
    def from_op(cls, op: TrackedAny, group: str = "primary") -> FlowEvent:
        """Create a FlowEvent from a TrackedAny operation."""

        if isinstance(op, TrackedForwardEvent):
            event_value = f"{op.amount:,.0f} sats"
        elif op.conv:
            event_value = op.conv.hive_sats_formatted_amount()
        else:
            event_value = ""  # ensure amount_str is populated for logging

        return cls(
            event_type="op",
            timestamp=getattr(op, "timestamp", datetime.now(tz=timezone.utc)),
            ledger_entry=None,
            op=op,
            group_id=getattr(op, "group_id", ""),
            short_id=getattr(op, "short_id", ""),
            ledger_type=None,
            op_type=getattr(op, "op_type", getattr(op, "type", "")),
            group=group,
            event_value=event_value,
        )

    @property
    def log_str(self) -> str:
        """Return a human-readable string summarizing this event for logging."""
        if self.event_type == "ledger" and self.ledger_entry:
            return self.ledger_entry.log_str
        if self.event_type == "op" and self.op:
            try:
                val = getattr(self.op, "log_str", None)
                if val:
                    return val
            except Exception:
                pass
        # Fallback: construct a useful string from the event's own fields
        parts: list[str] = []
        if self.op_type:
            parts.append(self.op_type)
        if self.ledger_type:
            parts.append(self.ledger_type.value)
        if self.short_id:
            parts.append(self.short_id)
        if self.event_value:
            parts.append(self.event_value)
        return " ".join(parts) if parts else "UnknownEvent"


class FlowInstance(BaseModel):
    """A tracked instance of a transaction flow.

    Collects FlowEvents and checks completeness against a FlowDefinition.
    This is the primary object for both real-time tracking and test assertions.
    """

    model_config = ConfigDict(extra="ignore")

    flow_definition: FlowDefinition = Field(
        ..., description="The flow definition this instance tracks"
    )
    trigger_group_id: str = Field("", description="Group ID of the triggering event")
    trigger_short_id: str = Field("", description="Short ID of the triggering event")
    cust_id: str = Field("", description="Customer ID associated with this flow")
    status: FlowStatus = Field(FlowStatus.PENDING, description="Current status of the flow")

    @field_validator("cust_id", mode="before")
    @classmethod
    def _normalize_cust_id(cls, value: Any) -> str:
        if value is None:
            return ""
        return str(value)

    started_at: datetime = Field(
        default_factory=lambda: datetime.now(tz=timezone.utc),
        description="When the flow was initiated",
    )
    completed_at: datetime | None = Field(None, description="When the flow completed")
    superset_grace_expires: datetime | None = Field(
        None,
        description="If this candidate was kept alive as a superset, when the grace period expires",
    )
    superset_winner_name: str | None = Field(
        None,
        description="Name of the sibling flow whose completion triggered the superset grace period",
    )
    events: List[FlowEvent] = Field(
        default_factory=list, description="Recorded events in this flow"
    )
    flow_value: str = Field("", description="Optional value for logging or notifications")
    last_stall_reported_at: datetime | None = Field(
        None, description="When the stall was last logged in the report loop"
    )

    def __init__(
        self,
        flow_definition: FlowDefinition,
        trigger_group_id: str = "",
        trigger_short_id: str = "",
        cust_id: str = "",
        status: FlowStatus = FlowStatus.PENDING,
        started_at: datetime | None = None,
        completed_at: datetime | None = None,
        events: List[FlowEvent] | None = None,
        flow_value: str = "",
        **data: Any,
    ) -> None:
        """Explicit initializer for FlowInstance.

        Pydantic generates a dynamic __init__ that confuses type checkers when
        we instantiate the model with positional/keyword arguments.  Providing
        this signature with defaults makes static analysis happy while still
        delegating to the BaseModel machinery.
        """
        # Deep-copy the definition so each instance has independent stages
        # whose op_log_str can be set without mutating the shared template.
        # When deserialising from Redis (model_validate_json), flow_definition
        # arrives as a plain dict — Pydantic will create a fresh object from
        # it, so no copy is needed.
        if isinstance(flow_definition, FlowDefinition):
            flow_definition = flow_definition.model_copy(deep=True)
        super().__init__(
            flow_definition=flow_definition,
            trigger_group_id=trigger_group_id,
            trigger_short_id=trigger_short_id,
            cust_id=cust_id,
            status=status,
            started_at=started_at or datetime.now(tz=timezone.utc),
            completed_at=completed_at,
            events=events or [],
            flow_value=flow_value,
            **data,
        )

    def add_event(self, event: FlowEvent) -> str | None:
        """Add an event and return the matched stage name, or None if unmatched.

        Only events that match a stage are appended to ``self.events``.
        Unmatched events are silently ignored so they don't pollute the
        event list or interfere with ``_resolve_candidates``.
        """
        # Snapshot which stages are already fulfilled BEFORE checking the event
        # so the new event isn't counted against itself.
        previously_matched = self.matched_stage_names

        # Try to match against stages not yet fulfilled
        for stage in self.flow_definition.stages:
            if stage.name not in previously_matched and stage.matches(event):
                # Event matched — record it
                stage.op_log_str = event.log_str
                self.events.append(event)
                if self.status == FlowStatus.PENDING:
                    self.status = FlowStatus.IN_PROGRESS

                if not self.flow_value and event.event_value:
                    self.flow_value = event.event_value

                if not self.cust_id and event.op and hasattr(event.op, "cust_id"):
                    self.cust_id = getattr(event.op, "cust_id")

                # Check completeness after adding — only record completed_at
                # the first time so late-event absorption doesn't push the
                # timestamp back and fall outside _LATE_EVENT_WINDOW.
                if self.is_complete and self.completed_at is None:
                    self.status = FlowStatus.COMPLETED
                    self.completed_at = event.timestamp
                return stage.name

        return None

    @property
    def matched_stage_names(self) -> set[str]:
        """Return names of stages that have been matched by events.

        Events are replayed **in order** and each event consumes at most
        one unmatched stage — the first one in definition order that
        accepts it.  This mirrors the behaviour of :pymethod:`add_event`
        and prevents a single ``transfer`` event from matching both
        ``trigger_transfer`` and ``change_transfer_op`` when matching is
        group-agnostic.
        """
        matched: set[str] = set()
        for event in self.events:
            for stage in self.flow_definition.stages:
                if stage.name not in matched and stage.matches(event):
                    matched.add(stage.name)
                    break  # this event is consumed — move to the next
        return matched

    @property
    def missing_stages(self) -> List[FlowStage]:
        """Return required stages that have not yet been fulfilled."""
        matched = self.matched_stage_names
        return [s for s in self.flow_definition.required_stages if s.name not in matched]

    @property
    def is_complete(self) -> bool:
        """Check if all required stages have been fulfilled."""
        return len(self.missing_stages) == 0

    @property
    def progress(self) -> str:
        """Human-readable progress summary."""
        total = len(self.flow_definition.required_stages)
        done = total - len(self.missing_stages)
        return f"{done}/{total} required stages complete"

    @property
    def duration(self) -> float | None:
        """Duration in seconds from start to completion, or None if not complete."""
        if self.completed_at:
            return (self.completed_at - self.started_at).total_seconds()
        return None

    @property
    def log_str(self) -> str:
        """Return a human-readable string summarizing this flow instance for logging."""
        name_str = from_snake_case(self.flow_definition.name)

        return (
            f"{name_str} for {self.cust_id} "
            f"{self.flow_value} "
            f"{self.trigger_short_id} "
            f"{self.status} "
            f"{self.progress}"
        )

    @property
    def notification_str(self) -> str:
        """Return a string summarizing this flow instance for notifications."""
        return self.log_str

    @property
    def log_extra(self) -> Dict[str, Any]:
        """
        Return extra fields for logging this flow instance.
        """
        return {"flow": self.summary()}

    def summary(self) -> dict[str, Any]:
        """Return a summary dict of this flow instance."""
        return {
            "flow_type": self.flow_definition.name,
            "trigger_group_id": self.trigger_group_id,
            "trigger_short_id": self.trigger_short_id,
            "cust_id": self.cust_id,
            "status": self.status.value,
            "progress": self.progress,
            "matched_stages": sorted(self.matched_stage_names),
            "missing_stages": [s.name for s in self.missing_stages],
            "event_count": len(self.events),
            "duration": self.duration,
        }


# ---------------------------------------------------------------------------
# Overwatch singleton: clean entry point for db_monitor integration
# ---------------------------------------------------------------------------

# Default timeout — if a flow hasn't received new events for this long it
# is marked as STALLED during the periodic report.
DEFAULT_STALL_TIMEOUT = timedelta(minutes=5)
DEFAULT_SUPERSET_GRACE_PERIOD = timedelta(seconds=30)
DEFAULT_TRIGGER_ONLY_TIMEOUT = timedelta(seconds=60)
DEFAULT_STALL_LOG_INTERVAL = timedelta(hours=1)


class Overwatch:
    """Singleton that ingests events, manages active flows, and reports progress.

    **State is persisted to Redis** so that in-progress and completed flows
    survive process restarts:

    - Active (pending / in_progress / stalled) flows are stored in a Redis
      hash at ``overwatch:flows:active`` keyed by
      ``<cust_id>:<trigger_group_id>:<flow_name>``.
    - Completed flows are moved to individual keys
      ``overwatch:flows:completed:<cust_id>:<trigger_group_id>:<flow_name>``
      with a 24-hour TTL so they stay queryable for at least a day.

    If Redis is unreachable the system continues to operate purely in-memory
    and will attempt to persist again on the next mutation.

    Usage::

        overwatch = Overwatch()
        await overwatch.ingest_ledger_entry(ledger_entry)
        await overwatch.ingest_op(op)

        # Start the periodic reporter as a long-running task:
        asyncio.create_task(
            overwatch.report_loop(interval=30, shutdown_event=shutdown_event)
        )
    """

    _instance: ClassVar[Overwatch | None] = None

    # ---- state (in-memory cache, synced to Redis) ----
    flow_instances: ClassVar[List[FlowInstance]] = []
    _flow_definitions: ClassVar[dict[str, FlowDefinition]] = {}
    stall_timeout: ClassVar[timedelta] = DEFAULT_STALL_TIMEOUT
    superset_grace_period: ClassVar[timedelta] = DEFAULT_SUPERSET_GRACE_PERIOD
    trigger_only_timeout: ClassVar[timedelta] = DEFAULT_TRIGGER_ONLY_TIMEOUT
    stall_log_interval: ClassVar[timedelta] = DEFAULT_STALL_LOG_INTERVAL
    _loaded_from_redis: ClassVar[bool] = False

    def __new__(cls) -> Overwatch:
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    # ---- flow definition registry ----

    @classmethod
    def register_flow(cls, definition: FlowDefinition) -> None:
        """Register a FlowDefinition so triggers can auto-create instances."""
        cls._flow_definitions[definition.name] = definition

    @classmethod
    def registered_flows(cls) -> dict[str, FlowDefinition]:
        """Return the currently registered flow definitions."""
        return dict(cls._flow_definitions)

    # ------------------------------------------------------------------
    # Redis persistence helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _redis():
        """Return the async Redis client, or ``None`` if unavailable."""
        try:
            return InternalConfig.redis_async
        except Exception:
            return None

    @staticmethod
    def _redis_flow_key(flow: FlowInstance) -> str:
        """Composite Redis key allowing multiple candidates per trigger."""
        return f"{flow.cust_id}:{flow.trigger_group_id}:{flow.flow_definition.name}"

    async def _persist_flow(self, flow: FlowInstance) -> None:
        """Write a single flow to Redis (active hash or completed key)."""
        r = self._redis()
        if r is None:
            return
        try:
            data = flow.model_dump_json()
            rkey = self._redis_flow_key(flow)
            if flow.status == FlowStatus.COMPLETED:
                key = f"{_REDIS_COMPLETED_PREFIX}{rkey}"
                await r.setex(key, _COMPLETED_TTL_SECONDS, data)
                # Remove from the active hash
                await r.hdel(_REDIS_ACTIVE_KEY, rkey)
            else:
                await r.hset(_REDIS_ACTIVE_KEY, rkey, data)
        except Exception as e:
            logger.warning(
                f"{ICON} Redis persist failed: {e}",
                extra={"notification": False},
            )

    async def _remove_active_flow(self, flow: FlowInstance) -> None:
        """Remove a flow from the active Redis hash."""
        r = self._redis()
        if r is None:
            return
        try:
            await r.hdel(_REDIS_ACTIVE_KEY, self._redis_flow_key(flow))
        except Exception:
            pass

    async def load_from_redis(self) -> int:
        """Hydrate in-memory state from Redis.

        Called once on startup (or manually).  Returns the number of flows
        loaded.  Already-loaded flows whose ``trigger_group_id`` is present in
        memory are skipped so hot-reloading is safe.
        """
        r = self._redis()
        if r is None:
            return 0
        loaded = 0
        existing_ids = {self._redis_flow_key(f) for f in self.flow_instances}
        try:
            # Active flows
            active_data: dict[str, str] = await r.hgetall(_REDIS_ACTIVE_KEY)
            for rkey, raw in active_data.items():
                if rkey in existing_ids:
                    continue
                try:
                    flow = FlowInstance.model_validate_json(raw)
                    normalized_rkey = self._redis_flow_key(flow)
                    # Restore event_filter callbacks from the registered
                    # definition (they are not serialised to Redis) while
                    # preserving per-instance op_log_str values.
                    if flow.flow_definition.name in self._flow_definitions:
                        registered = self._flow_definitions[flow.flow_definition.name]
                        for inst_stage, reg_stage in zip(
                            flow.flow_definition.stages, registered.stages
                        ):
                            inst_stage.event_filter = reg_stage.event_filter
                    # if definition change means the flow is now complete, fix status
                    if flow.is_complete and flow.status != FlowStatus.COMPLETED:
                        flow.status = FlowStatus.COMPLETED
                        flow.completed_at = (
                            flow.events[-1].timestamp if flow.events else flow.started_at
                        )
                        # also persist updated status immediately
                        await self._persist_flow(flow)
                    self.flow_instances.append(flow)
                    existing_ids.add(normalized_rkey)
                    loaded += 1
                    if normalized_rkey != rkey:
                        await r.hdel(_REDIS_ACTIVE_KEY, rkey)
                        if flow.status == FlowStatus.COMPLETED:
                            await r.setex(
                                f"{_REDIS_COMPLETED_PREFIX}{normalized_rkey}",
                                _COMPLETED_TTL_SECONDS,
                                flow.model_dump_json(),
                            )
                        else:
                            await r.hset(
                                _REDIS_ACTIVE_KEY,
                                normalized_rkey,
                                flow.model_dump_json(),
                            )
                except Exception as e:
                    logger.warning(
                        f"{ICON} Skipping corrupt active flow {rkey}: {e}",
                        extra={"notification": False},
                    )
            # Completed flows (scan for keys)
            cursor: int = 0
            while True:
                cursor, keys = await r.scan(
                    cursor,
                    match=f"{_REDIS_COMPLETED_PREFIX}*",
                    count=100,
                )
                for key in keys:
                    rkey = (
                        key.removeprefix(_REDIS_COMPLETED_PREFIX)
                        if isinstance(key, str)
                        else key.decode().removeprefix(_REDIS_COMPLETED_PREFIX)
                    )
                    if rkey in existing_ids:
                        continue
                    raw_val: str | None = await r.get(key)
                    if raw_val is None:
                        continue
                    try:
                        flow = FlowInstance.model_validate_json(raw_val)
                        normalized_rkey = self._redis_flow_key(flow)
                        self.flow_instances.append(flow)
                        existing_ids.add(normalized_rkey)
                        loaded += 1
                        if normalized_rkey != rkey:
                            await r.delete(key)
                            await r.setex(
                                f"{_REDIS_COMPLETED_PREFIX}{normalized_rkey}",
                                _COMPLETED_TTL_SECONDS,
                                flow.model_dump_json(),
                            )
                    except Exception as e:
                        logger.warning(
                            f"{ICON} Skipping corrupt completed flow {rkey}: {e}",
                            extra={"notification": False},
                        )
                if cursor == 0:
                    break
        except Exception as e:
            logger.warning(
                f"{ICON} Failed to load flows from Redis: {e}",
                extra={"notification": False},
            )
        if loaded:
            # compute status breakdown for reporting
            act = len(
                [
                    f
                    for f in self.flow_instances
                    if f.status not in (FlowStatus.COMPLETED, FlowStatus.FAILED)
                ]
            )
            stl = len([f for f in self.flow_instances if f.status == FlowStatus.STALLED])
            comp = len([f for f in self.flow_instances if f.status == FlowStatus.COMPLETED])
            logger.info(
                f"{ICON} Loaded {loaded} flow(s) from Redis ({act} active, {stl} stalled, {comp} completed)",
                extra={"notification": False},
            )
        Overwatch._loaded_from_redis = True
        return loaded

    async def _ensure_loaded(self) -> None:
        """Load from Redis once if not already done."""
        if not self._loaded_from_redis:
            await self.load_from_redis()

    # ---- event ingestion ----

    async def ingest_ledger_entry(
        self,
        ledger_entry: LedgerEntry,
        group: str = "primary",
    ) -> str | None:
        """Feed a ledger entry into overwatch.

        The entry is wrapped in a FlowEvent, matched against every active
        (non-completed) flow, and the matched stage name is returned (or
        ``None`` if no flow consumed it).
        """
        await self._ensure_loaded()
        event = FlowEvent.from_ledger_entry(ledger_entry, group=group)
        logger.info(
            f"{ICON} {ledger_entry.short_id} {ledger_entry.log_str}",
            extra={"notification": False, **ledger_entry.log_extra},
        )
        return await self._dispatch(event)

    async def ingest_op(
        self,
        op: TrackedAny,
        group: str = "primary",
    ) -> str | None:
        """Feed a TrackedAny operation into overwatch.

        If the op matches a registered trigger_op_type **and** no active flow
        already owns this ``group_id``, a new FlowInstance is automatically
        created.  Returns the matched stage name, or ``None``.
        """
        await self._ensure_loaded()
        event = FlowEvent.from_op(op, group=group)
        logger.info(
            f"{ICON} {op.short_id} {op.log_str}",
            extra={"notification": False, **op.log_extra},
        )

        # Auto-create a flow instance when a trigger op arrives
        matched = await self._dispatch(event)
        if matched is None:
            matched = await self._try_create_flow(event, op)

        # --- Detect payment-failure notifications that terminate flows ---
        #
        # Path 1: custom_json notification reply (parent_id + notification flag)
        json_data = getattr(op, "json_data", None)
        parent_id = getattr(json_data, "parent_id", None) if json_data else None
        is_notification = getattr(json_data, "notification", False) if json_data else False
        cj_memo = getattr(json_data, "memo", "") or ""
        if parent_id and is_notification and "Payment failed" in cj_memo:
            await self._complete_by_notification(reply_event=event, parent_id=parent_id)

        # Path 2: transfer refund (Hive/HBD returned to customer with
        # "Payment failed" in the memo and a § short_id back-reference).
        if not parent_id:
            op_memo = getattr(op, "memo", "") or ""
            if "Payment failed" in op_memo:
                ref_short_id = find_short_id(op_memo)
                if ref_short_id:
                    await self._complete_by_notification(
                        reply_event=event, trigger_short_id=ref_short_id
                    )

        return matched

    # ---- internal dispatch ----

    @staticmethod
    def _is_duplicate(flow: FlowInstance, event: FlowEvent) -> bool:
        """Check if an equivalent event was already added to *flow*.

        Prevents re-processing when MongoDB sends an *update* change-stream
        event for a document we already ingested on *insert* (e.g. the trigger
        op being updated with reply IDs).

        - **Op events** are deduped by ``(event_type, group_id)`` — each op
          has a unique ``group_id``.
        - **Ledger events** are deduped by ``(event_type, group_id,
          ledger_type)`` because several ledger entries can share the same
          ``group_id``.
        """
        for existing in flow.events:
            if existing.event_type != event.event_type:
                continue
            if existing.group_id != event.group_id:
                continue
            if event.event_type == "op":
                return True  # same group_id + event_type → duplicate op
            # ledger: also require matching ledger_type
            if existing.ledger_type == event.ledger_type:
                return True
        return False

    async def _dispatch(self, event: FlowEvent) -> str | None:
        """Try to match *event* against every active flow instance.

        Events are dispatched to **all** active flows (not just the first
        match) so that multiple candidate flows for the same trigger can
        accumulate stages in parallel.  When a candidate completes,
        :pymethod:`_resolve_candidates` removes the remaining candidates.

        If no active flow matches, recently completed flows are also
        checked so that late-arriving optional events (e.g. notifications)
        are absorbed rather than spawning spurious new candidates.

        Before attempting a match the event is checked for duplication —
        if a flow already contains an event with the same identity the
        flow is skipped.
        """
        first_result: str | None = None
        newly_completed: list[FlowInstance] = []
        for flow in self.active_flows:
            if self._is_duplicate(flow, event):
                continue
            result = flow.add_event(event)
            if result is not None:
                if first_result is None:
                    first_result = result
                # Clear superset grace only when the event is a
                # *distinguishing* one — i.e. it matches a stage the
                # candidate has but the simpler (winner) sibling does not.
                # Events that match *required* stages shared with the winner
                # (e.g. a notification custom_json common to both flows) are
                # NOT enough evidence that this candidate is the real flow.
                # Matching an optional-only stage in the winner IS
                # distinguishing because the winner completed without it.
                if flow.superset_grace_expires is not None:
                    winner_def = self._flow_definitions.get(flow.superset_winner_name or "")
                    shared_event = winner_def is not None and any(
                        s.matches(event) for s in winner_def.required_stages
                    )
                    if not shared_event:
                        flow.superset_grace_expires = None
                        flow.superset_winner_name = None
                if flow.is_complete:
                    newly_completed.append(flow)
                    message = f"{ICON} ✅ {Fore.WHITE}{flow.log_str} {Fore.RESET}"
                    asyncio.create_task(self._delay_log(flow, message))
                await self._persist_flow(flow)
        for completed in newly_completed:
            await self._resolve_candidates(completed)

        # Second pass: absorb late events into recently-completed flows
        # (e.g. notification custom_json arriving after all required stages).
        # Only consider flows that completed within _LATE_EVENT_WINDOW to
        # avoid greedily absorbing unrelated events from new transactions.
        if first_result is None:
            now = datetime.now(tz=timezone.utc)
            for flow in self.completed_flows:
                if (
                    flow.completed_at is not None
                    and (now - flow.completed_at) > _LATE_EVENT_WINDOW
                ):
                    continue
                if self._is_duplicate(flow, event):
                    continue
                result = flow.add_event(event)
                if result is not None:
                    first_result = result
                    message = (
                        f"{ICON} 📎 {Fore.YELLOW}Late event '{result}' absorbed by "
                        f"completed flow '{flow.flow_definition.name}' "
                        f"({flow.trigger_short_id}){Fore.RESET}"
                    )
                    asyncio.create_task(self._delay_log(flow, message, notification=False))
                    await self._persist_flow(flow)
                    break  # one match is enough

        return first_result

    async def _delay_log(
        self, flow: FlowInstance, message: str, notification: bool = True
    ) -> None:
        """
        Helper to log a message after a short delay, allowing the current flow state to settle.
        Also lets the process_tracked_events to complete.
        """
        await asyncio.sleep(1)
        logger.info(
            f"{message}",
            extra={
                "notification": notification,
                "notification_str": f"{ICON} ✅ {flow.notification_str}",
                **flow.log_extra,
            },
        )

    async def _try_create_flow(self, event: FlowEvent, op: TrackedAny) -> str | None:
        """If *event* matches registered triggers, create candidate FlowInstances.

        When multiple flow definitions share the same ``trigger_op_type`` a
        candidate instance is created for **each** matching definition.  As
        subsequent events arrive the correct candidate will naturally
        accumulate the right stages and complete; the losers are cleaned up
        by :pymethod:`_resolve_candidates`.
        """
        # Skip reply ops that reference a parent transaction.
        # Fee/notification custom_jsons have a parent_id linking them to the
        # original customer operation.  They are side-effects, not new customer
        # triggers, and would create false candidate flows that stall forever.
        json_data = getattr(op, "json_data", None)
        parent_id = getattr(json_data, "parent_id", None) if json_data else None
        if parent_id:
            logger.info(
                f"{ICON} ⏭️ Skipping flow creation for reply op "
                f"({event.short_id}, parent_id present)",
                extra={"notification": False},
            )
            return None

        # Skip transfers originating from internal/system accounts.
        # These are payouts, refunds, change returns, or internal moves —
        # never customer-initiated deposit flows.  Customer flows are always
        # triggered by an *external* account sending to the service account.
        from_acc = getattr(op, "from_account", "")
        to_acc = getattr(op, "to_account", "")
        if from_acc:
            try:
                hive_cfg = InternalConfig().config.hive_config
                # Include ALL server accounts (not just the first) plus
                # treasury, funding, exchange and exchange alternate names.
                internal = set(hive_cfg.extended_all_account_names + hive_cfg.server_account_names)
                if internal and from_acc in internal:
                    logger.info(
                        f"{ICON} ⏭️ Skipping flow creation for outbound transfer "
                        f"({from_acc} → {to_acc}, {event.short_id})",
                        extra={"notification": False},
                    )
                    return None
            except Exception:
                pass  # config unavailable — proceed normally

        first_result: str | None = None
        candidates: list[str] = []
        for defn in self._flow_definitions.values():
            if event.op_type == defn.trigger_op_type and event.group == "primary":
                # If the first (trigger) stage has an event_filter, check it
                # before creating an instance.  Without this guard a rejected
                # trigger can accidentally match a later same-type stage and
                # create a permanently stalled candidate.
                if defn.stages and not defn.stages[0].matches(event):
                    continue
                instance = FlowInstance(
                    flow_definition=defn,
                    trigger_group_id=event.group_id,
                    trigger_short_id=event.short_id,
                    cust_id=getattr(op, "from_account", ""),
                    status=FlowStatus.PENDING,
                    completed_at=None,
                )
                self.flow_instances.append(instance)
                result = instance.add_event(event)
                if first_result is None and result is not None:
                    first_result = result
                candidates.append(defn.name)
                await self._persist_flow(instance)
        if candidates:
            if len(candidates) == 1:
                logger.info(
                    f"{ICON} 🆕 New flow '{candidates[0]}' started "
                    f"({event.short_id}) cust={getattr(op, 'from_account', '')}",
                    extra={"notification": False},
                )
            else:
                logger.info(
                    f"{ICON} 🆕 {len(candidates)} candidate flows started "
                    f"({event.short_id}): {', '.join(candidates)}",
                    extra={"notification": False},
                )
        return first_result

    async def _complete_by_notification(
        self,
        reply_event: FlowEvent,
        parent_id: str | None = None,
        trigger_short_id: str | None = None,
    ) -> None:
        """Complete active flows when a notification reply arrives.

        A notification custom_json with ``parent_id`` signals that the server
        has finished processing the original transaction — success, failure,
        or refund.  This is the terminal event for all candidate flows sharing
        the ``trigger_group_id`` (custom_json path) or ``trigger_short_id``
        (transfer refund path).

        The most-progressed candidate is marked COMPLETED; the rest are
        cancelled as losing candidates.
        """
        matching = [
            f
            for f in self.active_flows
            if (parent_id and f.trigger_group_id == parent_id)
            or (trigger_short_id and f.trigger_short_id == trigger_short_id)
        ]
        if not matching:
            return

        # Pick the candidate with the most matched required stages.
        best = max(
            matching,
            key=lambda f: len(f.flow_definition.required_stages) - len(f.missing_stages),
        )

        # Force-complete the best candidate
        best.status = FlowStatus.COMPLETED
        best.completed_at = reply_event.timestamp
        logger.info(
            f"{ICON} ✅ {Fore.WHITE}Flow '{best.flow_definition.name}' "
            f"({best.trigger_short_id}) completed by notification reply"
            f"{Fore.RESET}",
            extra={
                "notification": True,
                "notification_str": f"{ICON} ✅ {best.notification_str}",
                **best.log_extra,
            },
        )
        await self._persist_flow(best)

        # Cancel remaining candidates
        for flow in matching:
            if flow is best:
                continue
            flow.status = FlowStatus.FAILED
            self.flow_instances.remove(flow)
            await self._remove_active_flow(flow)
            logger.info(
                f"{ICON} 🗑️ Removed candidate '{flow.flow_definition.name}' "
                f"({flow.trigger_short_id}) — completed by notification reply",
                extra={"notification": False, **flow.log_extra},
            )

    async def _resolve_candidates(self, winner: FlowInstance) -> None:
        """Remove losing candidate flows that share the same trigger.

        Called when *winner* completes.  A candidate is kept alive if:

        1. It already has **events** the winner's definition can't explain
           (e.g. a ``payment`` op not in the winner's stages), **or**
        2. The winner's stage definitions are a **proper subset** of the
           candidate's — meaning the candidate is a superset flow that
           could still be the correct match once more events arrive.

        Without check (2), a simple flow (e.g. ``keepsats_internal_transfer``
        with 2 required stages) would kill a superset candidate
        (``keepsats_to_hive`` with 12+ required stages) before the
        distinguishing events have a chance to arrive.
        """
        candidates = [
            f
            for f in self.flow_instances
            if f is not winner
            and f.trigger_group_id == winner.trigger_group_id
            and f.status not in (FlowStatus.COMPLETED, FlowStatus.FAILED)
        ]
        winner_stages = winner.flow_definition.stages

        def _stage_sig(s: FlowStage) -> tuple:
            """Hashable matching-criteria signature for a stage."""
            return (s.event_type, s.op_type, s.ledger_type)

        winner_sigs = {_stage_sig(s) for s in winner_stages}
        winner_req_sigs = {_stage_sig(s) for s in winner.flow_definition.required_stages}

        for candidate in candidates:
            # (1) Keep the candidate if it has events the winner can't explain
            has_unique_events = any(
                not any(stage.matches(ev) for stage in winner_stages) for ev in candidate.events
            )
            # (2) Keep if the candidate is a superset flow.  Two checks:
            #     a) All of the winner's stages exist in the candidate
            #        (matching by event_type + op_type + ledger_type), AND
            #        the candidate has additional stage signatures, OR
            #     b) Both flows have the same total stage signatures, but
            #        the candidate requires strictly more stages (i.e. the
            #        winner's required-stage sigs are a proper subset of
            #        the candidate's required-stage sigs).
            candidate_sigs = {_stage_sig(s) for s in candidate.flow_definition.stages}
            candidate_req_sigs = {_stage_sig(s) for s in candidate.flow_definition.required_stages}
            winner_is_proper_subset = winner_sigs.issubset(candidate_sigs) and (
                winner_sigs != candidate_sigs
                or (
                    winner_req_sigs.issubset(candidate_req_sigs)
                    and winner_req_sigs != candidate_req_sigs
                )
            )

            if has_unique_events or winner_is_proper_subset:
                reason = "has unique events" if has_unique_events else "is a superset flow"
                # Start the superset grace period so the candidate gets
                # cancelled automatically if no distinguishing events arrive.
                if winner_is_proper_subset and candidate.superset_grace_expires is None:
                    candidate.superset_grace_expires = (
                        datetime.now(tz=timezone.utc) + self.superset_grace_period
                    )
                    candidate.superset_winner_name = winner.flow_definition.name
                logger.info(
                    f"{ICON} 📌 Keeping candidate '{candidate.flow_definition.name}' "
                    f"({candidate.trigger_short_id}) — {reason} "
                    f"vs '{winner.flow_definition.name}'",
                    extra={"notification": False, **candidate.log_extra},
                )
                continue
            candidate.status = FlowStatus.FAILED
            self.flow_instances.remove(candidate)
            await self._remove_active_flow(candidate)
            logger.info(
                f"{ICON} 🗑️ Removed candidate '{candidate.flow_definition.name}' "
                f"({candidate.trigger_short_id}) — "
                f"'{winner.flow_definition.name}' completed",
                extra={"notification": False, **candidate.log_extra},
            )

    async def cancel_flows_for_trigger(self, trigger_group_id: str) -> int:
        """Cancel all candidate flows for a trigger that produced no ledger entries.

        Called by the processing pipeline when a trigger op (e.g. a transfer)
        turns out to be irrelevant — for example a transfer between untracked
        accounts.  Returns the number of flows cancelled.
        """
        cancelled = 0
        for flow in list(self.active_flows):
            if flow.trigger_group_id != trigger_group_id:
                continue
            flow.status = FlowStatus.FAILED
            self.flow_instances.remove(flow)
            await self._remove_active_flow(flow)
            cancelled += 1
            logger.info(
                f"{ICON} 🗑️ Cancelled '{flow.flow_definition.name}' "
                f"({flow.trigger_short_id}) — no ledger entries produced",
                extra={"notification": False, **flow.log_extra},
            )
        return cancelled

    # ---- queries ----

    @property
    def active_flows(self) -> List[FlowInstance]:
        """Return flow instances that are not yet completed or failed."""
        return [
            f
            for f in self.flow_instances
            if f.status not in (FlowStatus.COMPLETED, FlowStatus.FAILED)
        ]

    @property
    def completed_flows(self) -> List[FlowInstance]:
        """Return completed flow instances."""
        return [f for f in self.flow_instances if f.status == FlowStatus.COMPLETED]

    @property
    def stalled_flows(self) -> List[FlowInstance]:
        """Return stalled flow instances."""
        return [f for f in self.flow_instances if f.status == FlowStatus.STALLED]

    # ---- stall detection ----

    async def check_stalls(self, now: datetime | None = None) -> List[FlowInstance]:
        """Mark active flows that haven't received events recently as STALLED.

        Also cancels superset candidates whose grace period has expired —
        i.e. a simpler sibling flow already completed and this candidate
        hasn't accumulated any distinguishing events in time.

        Returns the list of flows whose status was changed.
        """
        now = now or datetime.now(tz=timezone.utc)
        newly_stalled: List[FlowInstance] = []

        # Rule 1: cancel superset candidates past their grace period
        for flow in list(self.active_flows):
            if flow.superset_grace_expires is not None and now >= flow.superset_grace_expires:
                flow.status = FlowStatus.FAILED
                self.flow_instances.remove(flow)
                await self._remove_active_flow(flow)
                logger.info(
                    f"{ICON} 🗑️ Superset candidate '{flow.flow_definition.name}' "
                    f"({flow.trigger_short_id}) cancelled — grace period "
                    f"({self.superset_grace_period.total_seconds():.0f}s) expired",
                    extra={"notification": False, **flow.log_extra},
                )

        # Rule 2: cancel flows that haven't progressed past trigger-only.
        # A flow created by _try_create_flow receives exactly one "op" event
        # (the trigger).  If no subsequent stage-matched events arrive within
        # trigger_only_timeout, the trigger was likely for an irrelevant op
        # (e.g. a server-to-exchange transfer) and the flow should be cleaned up.
        for flow in list(self.active_flows):
            if flow.superset_grace_expires is not None:
                continue  # handled by Rule 1
            if (
                len(flow.events) == 1
                and flow.events[0].event_type == "op"
                and now - flow.started_at > self.trigger_only_timeout
            ):
                flow.status = FlowStatus.FAILED
                self.flow_instances.remove(flow)
                await self._remove_active_flow(flow)
                logger.info(
                    f"{ICON} 🗑️ Flow '{flow.flow_definition.name}' "
                    f"({flow.trigger_short_id}) cancelled — trigger-only "
                    f"timeout ({self.trigger_only_timeout.total_seconds():.0f}s) "
                    f"expired, no subsequent events matched",
                    extra={"notification": False, **flow.log_extra},
                )

        for flow in list(self.active_flows):
            # Already stalled — nothing new to report.
            if flow.status == FlowStatus.STALLED:
                continue

            # a definition change may have made the flow complete
            if flow.is_complete and flow.status != FlowStatus.COMPLETED:
                flow.status = FlowStatus.COMPLETED
                flow.completed_at = flow.events[-1].timestamp if flow.events else flow.started_at
                await self._persist_flow(flow)
                continue

            last_event_time = flow.events[-1].timestamp if flow.events else flow.started_at
            if now - last_event_time > self.stall_timeout:
                flow.status = FlowStatus.STALLED
                newly_stalled.append(flow)
                logger.warning(
                    f"{ICON} ⚠️ Flow '{flow.flow_definition.name}' "
                    f"({flow.trigger_short_id}) stalled — "
                    f"{flow.progress}, last event {last_event_time:%H:%M:%S} "
                    f"{flow.log_str}",
                    extra={
                        "notification": True,
                        "error_code": "overwatch_flow_stalled",
                        **flow.log_extra,
                    },
                )
                await self._persist_flow(flow)
        return newly_stalled

    # ---- periodic reporter ----

    async def report_loop(
        self,
        interval: float = 30,
        shutdown_event: asyncio.Event | None = None,
    ) -> None:
        """Long-running coroutine that periodically logs flow status.

        On the first iteration it hydrates state from Redis so that flows
        started before a restart are picked up again.

        Args:
            interval: Seconds between reports.
            shutdown_event: When set, the loop exits gracefully.
        """
        await self._ensure_loaded()
        logger.info(
            f"{ICON} Overwatch report loop started (interval={interval}s)",
            extra={"notification": False},
        )
        while True:
            if shutdown_event and shutdown_event.is_set():
                break
            try:
                await self.check_stalls()
                self._log_report()
            except Exception as e:
                logger.error(
                    f"{ICON} Error in overwatch report loop: {e}",
                    extra={"error_code": "overwatch_report_error"},
                )
            # Sleep in small increments so we can break promptly on shutdown
            for _ in range(int(interval)):
                if shutdown_event and shutdown_event.is_set():
                    break
                await asyncio.sleep(1)

        logger.info(
            f"{ICON} Overwatch report loop stopped",
            extra={"notification": False},
        )

    def _log_report(self) -> None:
        """Emit a single log line summarising current state."""
        active = self.active_flows
        stalled = self.stalled_flows
        completed = self.completed_flows

        if not active and not stalled:
            return  # nothing interesting to report

        parts: list[str] = [f"{ICON} Overwatch:"]
        if active:
            parts.append(f"{len(active)} active")
        if stalled:
            parts.append(f"{len(stalled)} stalled")
        parts.append(f"{len(completed)} completed")
        logger.info(" | ".join(parts), extra={"notification": False})

        for flow in active:
            logger.info(
                f"{ICON}   ↳ {flow.flow_definition.name} "
                f"({flow.trigger_short_id}) {flow.progress} Started: {flow.started_at}",
                extra={"notification": False, **flow.log_extra},
            )
        for flow in stalled:
            now = datetime.now(tz=timezone.utc)
            # Throttle stall log lines: only log once per stall_log_interval
            if (
                flow.last_stall_reported_at is not None
                and now - flow.last_stall_reported_at < self.stall_log_interval
            ):
                continue
            flow.last_stall_reported_at = now
            stalled_time = flow.events[-1].timestamp if flow.events else flow.started_at
            since = now - stalled_time
            logger.info(
                f"{ICON}   ↳ STALLED {flow.flow_definition.name} "
                f"({flow.trigger_short_id}) {flow.progress} "
                f"stalled for: {since}",
                extra={"notification": False},
            )

    # ---- housekeeping ----

    @classmethod
    def reset(cls) -> None:
        """Clear all in-memory state — useful for tests."""
        cls.flow_instances.clear()
        cls._flow_definitions.clear()
        cls.stall_timeout = DEFAULT_STALL_TIMEOUT
        cls.superset_grace_period = DEFAULT_SUPERSET_GRACE_PERIOD
        cls.trigger_only_timeout = DEFAULT_TRIGGER_ONLY_TIMEOUT
        cls.stall_log_interval = DEFAULT_STALL_LOG_INTERVAL
        cls._loaded_from_redis = False
        cls._instance = None

    async def reset_redis(self) -> None:
        """Clear all overwatch data from Redis."""
        r = self._redis()
        if r is None:
            return
        try:
            await r.delete(_REDIS_ACTIVE_KEY)
            cursor: int = 0
            while True:
                cursor, keys = await r.scan(
                    cursor,
                    match=f"{_REDIS_COMPLETED_PREFIX}*",
                    count=100,
                )
                if keys:
                    await r.delete(*keys)
                if cursor == 0:
                    break
        except Exception as e:
            logger.warning(
                f"{ICON} Failed to clear Redis overwatch data: {e}",
                extra={"notification": False},
            )
