balance = {'Assets': defaultdict(<class 'dict'>,
                       {'Converted Hive Offset': {'Total': {'hbd': 39.98022,
                                                            'historical_usd': 39.00936,
                                                            'hive': 184.66608,
                                                            'msats': 36353120.77346,
                                                            'sats': 36345.66445,
                                                            'usd': 39.98022},
                                                  'devser.v4vapp': {'hbd': 39.98022,
                                                                    'hive': 184.66608,
                                                                    'msats': 36353120.77346,
                                                                    'sats': 36345.66445,
                                                                    'usd': 39.98022}},
                        'Customer Deposits Hive': {'Total': {'hbd': 39.98022,
                                                             'historical_usd': 39.00955,
                                                             'hive': 184.66608,
                                                             'msats': 36353120.77346,
                                                             'sats': 36345.66445,
                                                             'usd': 39.98022},
                                                   'devser.v4vapp': {'hbd': 39.98022,
                                                                     'hive': 184.66608,
                                                                     'msats': 36353120.77346,
                                                                     'sats': 36345.66445,
                                                                     'usd': 39.98022}},
                        'External Lightning Payments': {'Total': {'hbd': 0.0,
                                                                  'historical_usd': 0.0,
                                                                  'hive': 0.0,
                                                                  'msats': 0.0,
                                                                  'sats': 0.0,
                                                                  'usd': 0.0},
                                                        'umbrel': {'hbd': 0.0,
                                                                   'hive': 0.0,
                                                                   'msats': 0.0,
                                                                   'sats': 0.0,
                                                                   'usd': 0.0}},
                        'Total': {'hbd': 79.96044,
                                  'historical_usd': 78.8033,
                                  'hive': 369.33216,
                                  'msats': 72706241.54692,
                                  'sats': 72691.3289,
                                  'usd': 79.96044},
                        'Treasury Lightning': {'Total': {'hbd': 0.0,
                                                         'historical_usd': 0.78439,
                                                         'hive': 0.0,
                                                         'msats': 0.0,
                                                         'sats': 0.0,
                                                         'usd': 0.0},
                                               'umbrel': {'hbd': 0.0,
                                                          'hive': 0.0,
                                                          'msats': 0.0,
                                                          'sats': 0.0,
                                                          'usd': 0.0}}}),
 'Equity': defaultdict(<class 'dict'>,
                       {'Retained Earnings': {'Total': {'hbd': 2.37443,
                                                        'historical_usd': 0.0,
                                                        'hive': 10.96733,
                                                        'msats': 2159014.04403,
                                                        'sats': 2158.57121,
                                                        'usd': 2.37443},
                                              'umbrel': {'hbd': 2.37443,
                                                         'hive': 10.96733,
                                                         'msats': 2159014.04403,
                                                         'sats': 2158.57121,
                                                         'usd': 2.37443}},
                        'Total': {'hbd': 2.37443,
                                  'hive': 10.96733,
                                  'msats': 2159014.04403,
                                  'sats': 2158.57121,
                                  'usd': 2.37443}}),
 'Liabilities': defaultdict(<class 'dict'>,
                            {'Customer Liability Hive': {'Total': {'hbd': 0.0,
                                                                   'historical_usd': -4e-05,
                                                                   'hive': 0.0,
                                                                   'msats': 0.0,
                                                                   'sats': 0.0,
                                                                   'usd': 0.0},
                                                         'v4vapp-test': {'hbd': 0.0,
                                                                         'hive': 0.0,
                                                                         'msats': 0.0,
                                                                         'sats': 0.0,
                                                                         'usd': 0.0}},
                             'Total': {'hbd': 0.0,
                                       'historical_usd': -4e-05,
                                       'hive': 0.0,
                                       'msats': 0.0,
                                       'sats': 0.0,
                                       'usd': 0.0}}),
 'Total Liabilities and Equity': {'hbd': 2.37443,
                                  'hive': 10.96733,
                                  'msats': 2159014.04403,
                                  'sats': 2158.57121,
                                  'usd': 2.37443},
 'is_balanced': False,
 'reporting_date': datetime.datetime(2025, 7, 3, 15, 3, 45, 270321, tzinfo=datetime.timezone.utc),
 'spot_rates': {'hbd_to_usd': 1.0,
                'hive_to_usd': 0.21650004688161253,
                'msats_to_usd': 1.0997739519532044e-06,
                'sats_to_usd': 0.0010999995708154506}}
